# Generated by Django 5.2.3 on 2025-07-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testit', '0002_testcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.TextField(blank=True),
        ),
    ]
