# Generated by Django 5.2.3 on 2025-07-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testit', '0005_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='solved_questions',
            field=models.ManyToManyField(blank=True, related_name='solved_userProfiles', to='testit.question'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tried_questions',
            field=models.ManyToManyField(blank=True, related_name='tried_userProfiles', to='testit.question'),
        ),
    ]
