# Generated by Django 5.2.3 on 2025-07-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testit', '0006_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('questions', models.ManyToManyField(related_name='contests', to='testit.question')),
            ],
        ),
    ]
