# Generated by Django 5.2.3 on 2025-07-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testit', '0007_contest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='Tags',
            field=models.ManyToManyField(blank=True, to='testit.tag'),
        ),
    ]
